package com.komatsu.ahs.fleet.kafka;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.komatsu.ahs.fleet.metrics.FleetMetricsExporter;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.stereotype.Component;

/**
 * Alert Consumer for Flink CEP Alerts
 * 
 * Consumes alerts generated by Flink CEP patterns and updates
 * Prometheus metrics for visualization in Grafana.
 * 
 * CEP Alert Types:
 * - RAPID_DECELERATION: Speed drops from >50 kph to <10 kph in 5 seconds
 * - LOW_FUEL: Fuel level below 15%
 * - OVERHEATING: Engine temperature >95°C for 3 consecutive readings
 * - HIGH_TEMPERATURE: Engine temperature threshold exceeded
 * - TIRE_PRESSURE_LOW: Tire pressure below safe threshold
 */
@Component
@RequiredArgsConstructor
@Slf4j
public class AlertConsumer {

    private final FleetMetricsExporter metricsExporter;
    private final ObjectMapper objectMapper;
    
    @KafkaListener(
        topics = "${kafka.topics.vehicle-alerts:ahs.vehicle.alerts}",
        groupId = "${kafka.consumer.group-id}-alerts",
        containerFactory = "kafkaListenerContainerFactory"
    )
    public void consumeAlert(String message) {
        try {
            JsonNode alertNode = objectMapper.readTree(message);
            
            // Handle both snake_case (from Flink) and camelCase (legacy) field names
            String vehicleId = getFieldValue(alertNode, "vehicle_id", "vehicleId");
            String alertType = getFieldValue(alertNode, "alert_type", "alertType");
            String severity = getFieldValue(alertNode, "severity", "severity");
            String alertMessage = getFieldValue(alertNode, "message", "message");
            
            log.info("CEP Alert received - Vehicle: {}, Type: {}, Severity: {}, Message: {}",
                vehicleId, alertType, severity, alertMessage);
            
            // Update Prometheus metrics based on severity
            switch (severity.toUpperCase()) {
                case "CRITICAL":
                case "EMERGENCY":
                    metricsExporter.incrementCriticalAlert();
                    log.warn("CRITICAL ALERT for {}: {}", vehicleId, alertMessage);
                    break;
                case "WARNING":
                    metricsExporter.incrementWarningAlert();
                    break;
                case "ERROR":
                    metricsExporter.incrementErrorAlert();
                    break;
                case "INFO":
                    metricsExporter.incrementInfoAlert();
                    break;
                default:
                    log.debug("Unknown severity: {}", severity);
            }
            
            // Update CEP-specific metrics by alert type
            metricsExporter.incrementCepAlertByType(alertType);
            
        } catch (Exception e) {
            log.error("Error processing CEP alert: {}", message, e);
        }
    }
    
    /**
     * Get field value trying multiple possible field names (snake_case and camelCase)
     */
    private String getFieldValue(JsonNode node, String... fieldNames) {
        for (String fieldName : fieldNames) {
            JsonNode valueNode = node.get(fieldName);
            if (valueNode != null && !valueNode.isNull() && !valueNode.asText().isEmpty()) {
                return valueNode.asText();
            }
        }
        return "";
    }
}
