package com.komatsu.ahs.fleet.kafka;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.komatsu.ahs.fleet.metrics.FleetMetricsExporter;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.stereotype.Component;

/**
 * Alert Consumer for Flink CEP Alerts
 * 
 * Consumes alerts generated by Flink CEP patterns and updates
 * Prometheus metrics for visualization in Grafana.
 * 
 * CEP Alert Types:
 * - RAPID_DECELERATION: Speed drops from >50 kph to <10 kph in 5 seconds
 * - LOW_FUEL: Fuel level below 15%
 * - OVERHEATING: Engine temperature >95°C for 3 consecutive readings
 * - HIGH_TEMPERATURE: Engine temperature threshold exceeded
 * - TIRE_PRESSURE_LOW: Tire pressure below safe threshold
 */
@Component
@RequiredArgsConstructor
@Slf4j
public class AlertConsumer {

    private final FleetMetricsExporter metricsExporter;
    private final ObjectMapper objectMapper;
    
    @KafkaListener(
        topics = "${kafka.topics.vehicle-alerts:ahs.vehicle.alerts}",
        groupId = "${kafka.consumer.group-id}-alerts",
        containerFactory = "kafkaListenerContainerFactory"
    )
    public void consumeAlert(String message) {
        try {
            JsonNode alertNode = objectMapper.readTree(message);
            
            String vehicleId = alertNode.path("vehicleId").asText();
            String alertType = alertNode.path("alertType").asText();
            String severity = alertNode.path("severity").asText();
            String alertMessage = alertNode.path("message").asText();
            
            log.info("CEP Alert received - Vehicle: {}, Type: {}, Severity: {}, Message: {}",
                vehicleId, alertType, severity, alertMessage);
            
            // Update Prometheus metrics based on severity
            switch (severity.toUpperCase()) {
                case "CRITICAL":
                case "EMERGENCY":
                    metricsExporter.incrementCriticalAlert();
                    log.warn("CRITICAL ALERT for {}: {}", vehicleId, alertMessage);
                    break;
                case "WARNING":
                    metricsExporter.incrementWarningAlert();
                    break;
                case "ERROR":
                    metricsExporter.incrementErrorAlert();
                    break;
                default:
                    log.debug("Unknown severity: {}", severity);
            }
            
            // Update CEP-specific metrics by alert type
            metricsExporter.incrementCepAlertByType(alertType);
            
        } catch (Exception e) {
            log.error("Error processing CEP alert: {}", message, e);
        }
    }
}
